spring:
  jackson:
    defaultPropertyInclusion: non-null
    deserialization:
      failOnUnknownProperties: false
    mapper:
      accept-case-insensitive-enums: true
  datasource:
#    url: jdbc:h2:file:/data/demo
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  security:
    user:
      name: admin
      password: password1
